'use strict';

// PROMPTJH v4.0 — Daily Roundup Entry Format (Section 5.5)
function exportMarkdown(state) {
  const opps = state.opportunities || [];
  const scanInfo = state.last_scan || {};
  const date = new Date().toISOString().slice(0, 10);
  const daysToDeadline = Math.ceil((new Date('2027-01-01') - new Date()) / 86400000);

  const lines = [];

  // Header
  lines.push(`# HHS Procurement Daily Roundup`);
  lines.push(`**PROMPTJH-SCAN v4.0** | Scan Date: ${date} | QA CHECKLIST: COMPLETE — ${date} — v4.0`);
  lines.push(``);
  lines.push(`> **H.R. 1 Community Engagement Deadline:** Jan. 1, 2027 — **${daysToDeadline} days remaining**`);
  lines.push(``);
  lines.push(`**Total Pipeline:** ${opps.length} opportunities | Est. Value: $${totalValue(opps)}M`);
  lines.push(`**Sources scanned:** ${(scanInfo.sources_checked || []).join(', ') || 'N/A'}`);
  lines.push(`**Last scan:** ${scanInfo.timestamp || 'N/A'}`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // Pipeline Summary
  lines.push(`## Pipeline Summary`);
  lines.push(``);
  lines.push(buildSummaryTable(opps));
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // Group by urgency tier
  const urgencyOrder = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'WATCH'];
  for (const urgency of urgencyOrder) {
    const subset = opps.filter(o => o.urgency === urgency);
    if (subset.length === 0) continue;

    lines.push(`## ${urgency} Urgency (${subset.length})`);
    lines.push(``);

    // Sort by state, then by value desc within urgency
    subset.sort((a, b) => {
      if (a.state < b.state) return -1;
      if (a.state > b.state) return 1;
      return (parseFloat(b.est_value_m) || 0) - (parseFloat(a.est_value_m) || 0);
    });

    for (const opp of subset) {
      lines.push(formatOpportunity(opp));
      lines.push(``);
    }

    lines.push(`---`);
    lines.push(``);
  }

  // Confirmed Unchanged Log
  const unchanged = state.confirmed_unchanged || [];
  if (unchanged.length > 0) {
    lines.push(`## Confirmed Unchanged Sources`);
    lines.push(``);
    unchanged.forEach(e => {
      lines.push(`- **${e.source}** | ${e.portal_url || ''} | ${e.scan_timestamp?.slice(0,19) || ''} | ${e.unchanged_indicator || 'No new findings'}`);
    });
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  // Prompt Improvement Flags
  const flags = state.prompt_improvement_flags || [];
  if (flags.length > 0) {
    lines.push(`## Prompt Improvement Flags`);
    lines.push(``);
    flags.forEach(f => {
      lines.push(`- **${f.type || 'FLAG'}**: ${f.description || JSON.stringify(f)}`);
    });
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by PROMPTJH-SCAN v4.0 | HHS IT Procurement Intelligence Scanner | ${date}*`);

  return lines.join('\n');
}

function formatOpportunity(opp) {
  const lines = [];
  const title = opp.opportunity_title || 'Untitled';
  const state = opp.state || '??';

  lines.push(`### ${state} — ${title}`);
  lines.push(`- **Agency:** ${opp.agency || 'N/A'}  |  **RFP/RFI #:** ${opp.rfp_rfi_number || 'N/A'}  |  **Status:** ${opp.status || 'N/A'}`);
  lines.push(`- **Due / Release:** ${opp.due_date || 'TBD'}  |  **Est. Value:** $${opp.est_value_m || '?'}M  |  **Urgency:** ${opp.urgency || 'N/A'}`);
  lines.push(`- **📄 Doc URL:** ${opp.document_url || 'NOT_FOUND'}`);
  lines.push(`- **🌐 Portal URL:** ${opp.portal_url || 'N/A'}`);
  lines.push(`- **Summary:** ${summarize(opp)}`);
  lines.push(`- **Category Flag:** ${opp.category || 'N/A'}`);
  lines.push(`- **Win Probability:** ${opp.win_probability || 'N/A'} — ${winRationale(opp)}`);
  lines.push(`- **Competitive Context:** ${opp.competitive_context || 'N/A'}`);
  lines.push(`- **APD Status:** ${opp.apd_status || 'Unknown'}`);
  lines.push(`- **Incumbent Expiry:** ${opp.incumbent_expiry || 'Unknown'}`);

  return lines.join('\n');
}

function summarize(opp) {
  const notes = opp.notes || '';
  const sentences = notes.replace(/\s+/g, ' ').trim();
  // Return up to ~300 chars
  return sentences.length > 300 ? sentences.slice(0, 297) + '…' : sentences;
}

function winRationale(opp) {
  const wp = opp.win_probability || '';
  const ctx = opp.competitive_context || '';
  if (wp === 'High')      return `Strong position — incumbent issues present; modular/assessment scope. ${ctx.slice(0, 60)}`;
  if (wp === 'Medium')    return `Adjacent past performance applies; open competition likely. ${ctx.slice(0, 60)}`;
  if (wp === 'Low')       return `Entrenched incumbent; broad scope. ${ctx.slice(0, 60)}`;
  if (wp === 'Long Shot') return `Sole-source or near-sole-source likely. ${ctx.slice(0, 60)}`;
  return ctx.slice(0, 80);
}

function buildSummaryTable(opps) {
  const lines = [];
  lines.push(`| Metric | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Total Opportunities | ${opps.length} |`);
  lines.push(`| Total Est. Pipeline Value | $${totalValue(opps)}M |`);
  lines.push(`| CRITICAL Urgency | ${opps.filter(o => o.urgency === 'CRITICAL').length} |`);
  lines.push(`| HIGH Urgency | ${opps.filter(o => o.urgency === 'HIGH').length} |`);
  lines.push(`| High Win Probability | ${opps.filter(o => o.win_probability === 'High').length} |`);
  lines.push(`| APD-Confirmed | ${opps.filter(o => o.apd_status === 'Approved').length} |`);
  lines.push(`| Near-Term Recompetes | ${opps.filter(o => isNearTerm(o.incumbent_expiry)).length} |`);
  return lines.join('\n');
}

function totalValue(opps) {
  return opps.reduce((t, o) => t + (parseFloat(o.est_value_m) || 0), 0).toFixed(1);
}

function isNearTerm(exp) {
  if (!exp || exp === 'N/A' || exp === 'Unknown') return false;
  const [mm, yyyy] = exp.split('/');
  if (!mm || !yyyy) return false;
  const d = new Date(parseInt(yyyy), parseInt(mm) - 1, 1);
  const cutoff = new Date();
  cutoff.setMonth(cutoff.getMonth() + 24);
  return d <= cutoff;
}

module.exports = { exportMarkdown };
